# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c613824a469d5136241a6709f55b788c887d592f500427b15e7de9eb2d77ed0f64bc18b6177d854ddd33cb484f4d475a8d5c002b116f0eecd70f74d860a20287

test:
  secret_key_base: dcabed1c8601eeea848b8828250f502a3d40aaefd9de9f937df0968ab8ba0fe12318d2eaa4d8c6618c4418e6a44a9098c47d5d45e3fab9f220e92b9e58df9274

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
